name: Auto Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v6

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: install-uv
        run: pip install uv

      - name: build-package
        run: uv build

      - name: publish-package
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token $PYPI_API_TOKEN

      - name: create-release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          body: "Auto Release (${{ github.ref_name }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
